-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.association_officers (
  officer_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  full_name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  position character varying,
  association_name character varying,
  contact_number character varying,
  address text,
  term_start_date date,
  term_end_date date,
  term_duration character varying,
  farmers_under_supervision integer DEFAULT 0,
  profile_completed boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT true,
  remarks text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  last_login timestamp with time zone,
  profile_completed_at timestamp with time zone,
  profile_picture text,
  is_super_admin boolean DEFAULT false,
  CONSTRAINT association_officers_pkey PRIMARY KEY (officer_id)
);
CREATE TABLE public.auth_audit_log (
  log_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  user_type character varying CHECK (user_type::text = ANY (ARRAY['farmer'::character varying, 'buyer'::character varying, 'officer'::character varying]::text[])),
  action character varying NOT NULL,
  ip_address character varying,
  user_agent text,
  success boolean DEFAULT true,
  error_message text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT auth_audit_log_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.buyers (
  buyer_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_name character varying NOT NULL,
  owner_name character varying NOT NULL,
  business_address text,
  contact_number character varying,
  email character varying NOT NULL UNIQUE,
  license_or_accreditation character varying,
  buying_schedule character varying,
  buying_location text,
  warehouse_address text,
  accepted_quality_grades ARRAY,
  price_range_min numeric,
  price_range_max numeric,
  payment_terms character varying,
  partnered_associations ARRAY,
  password_hash character varying NOT NULL,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  remarks text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  last_login timestamp with time zone,
  profile_photo text,
  valid_id_photo text,
  business_permit_photo text,
  verification_status character varying DEFAULT 'pending'::character varying CHECK (verification_status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'rejected'::character varying]::text[])),
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  CONSTRAINT buyers_pkey PRIMARY KEY (buyer_id),
  CONSTRAINT buyers_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.association_officers(officer_id)
);
CREATE TABLE public.farmers (
  farmer_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  full_name character varying NOT NULL,
  sex character varying CHECK (sex::text = ANY (ARRAY['Male'::character varying, 'Female'::character varying, 'Other'::character varying]::text[])),
  age integer CHECK (age >= 18 AND age <= 100),
  contact_number character varying,
  address text,
  barangay character varying,
  municipality character varying,
  association_name character varying,
  farm_location text,
  farm_coordinates character varying,
  farm_area_hectares numeric,
  years_in_farming integer,
  type_of_abaca_planted character varying,
  average_harvest_volume_kg numeric,
  harvest_frequency_weeks integer,
  selling_price_range_min numeric,
  selling_price_range_max numeric,
  regular_buyer character varying,
  income_per_cycle numeric,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  remarks text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  last_login timestamp with time zone,
  profile_photo text,
  valid_id_photo text,
  verification_status character varying DEFAULT 'pending'::character varying CHECK (verification_status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'rejected'::character varying]::text[])),
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  CONSTRAINT farmers_pkey PRIMARY KEY (farmer_id),
  CONSTRAINT farmers_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.association_officers(officer_id)
);
CREATE TABLE public.maintenance_logs (
  log_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['enabled'::character varying, 'disabled'::character varying]::text[])),
  enabled_by uuid,
  reason text,
  ip_address character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT maintenance_logs_pkey PRIMARY KEY (log_id),
  CONSTRAINT maintenance_logs_enabled_by_fkey FOREIGN KEY (enabled_by) REFERENCES public.association_officers(officer_id)
);
CREATE TABLE public.refresh_tokens (
  token_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  user_type character varying NOT NULL CHECK (user_type::text = ANY (ARRAY['farmer'::character varying, 'buyer'::character varying, 'officer'::character varying]::text[])),
  token_hash character varying NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  revoked boolean DEFAULT false,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (token_id)
);
CREATE TABLE public.seedlings (
  seedling_id uuid NOT NULL DEFAULT gen_random_uuid(),
  variety character varying NOT NULL,
  source_supplier character varying,
  quantity_distributed integer NOT NULL CHECK (quantity_distributed > 0),
  date_distributed date NOT NULL DEFAULT CURRENT_DATE,
  recipient_farmer_id uuid,
  recipient_association character varying,
  remarks text,
  status character varying DEFAULT 'distributed'::character varying,
  distributed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  seedling_photo text,
  packaging_photo text,
  quality_photo text,
  planting_date date,
  planting_location text,
  planting_photo_1 text,
  planting_photo_2 text,
  planting_photo_3 text,
  planting_notes text,
  planted_by uuid,
  planted_at timestamp with time zone,
  CONSTRAINT seedlings_pkey PRIMARY KEY (seedling_id),
  CONSTRAINT seedlings_distributed_by_fkey FOREIGN KEY (distributed_by) REFERENCES public.association_officers(officer_id),
  CONSTRAINT seedlings_planted_by_fkey FOREIGN KEY (planted_by) REFERENCES public.farmers(farmer_id),
  CONSTRAINT seedlings_recipient_farmer_id_fkey FOREIGN KEY (recipient_farmer_id) REFERENCES public.farmers(farmer_id)
);
CREATE TABLE public.system_settings (
  setting_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value text NOT NULL,
  description text,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT system_settings_pkey PRIMARY KEY (setting_id),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.association_officers(officer_id)
);